module.exports = {
    "locations": [ [ "overworld", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "overworld", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "overworld", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "overworld", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "overworld", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "overworld", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "overworld", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "overworld", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "overworld", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "overworld", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "overworld", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "overworld", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "overworld", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "overworld", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "overworld", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "overworld", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "overworld", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "overworld", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "overworld", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "overworld", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "overworld", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "overworld", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "overworld", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "overworld", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "overworld", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "overworld", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "overworld", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "overworld", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "overworld", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "overworld", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "overworld", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "overworld", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "overworld", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "overworld", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "overworld", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "overworld", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "overworld", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "overworld", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "overworld", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "overworld", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "overworld", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "overworld", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "overworld", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "overworld", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "overworld", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "overworld", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "overworld", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "overworld", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "overworld", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "overworld", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "overworld", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "overworld", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "overworld", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "overworld", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "overworld", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "overworld", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "overworld", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "overworld", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "overworld", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "overworld", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "overworld", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "overworld", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "overworld", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "overworld", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "overworld", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "overworld", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "overworld", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "overworld", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "overworld", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "overworld", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "overworld", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "overworld", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "overworld", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "overworld", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "overworld", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "overworld", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "overworld", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "overworld", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "overworld", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "overworld", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "overworld", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "overworld", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "overworld", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "overworld", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "overworld", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "overworld", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "overworld", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "overworld", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "overworld", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "overworld", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "overworld", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "overworld", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "overworld", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "overworld", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "overworld", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "overworld", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "overworld", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "overworld", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "overworld", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "overworld", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "overworld", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "overworld", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "overworld", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "overworld", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "overworld", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "overworld", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "overworld", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "overworld", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "overworld", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "overworld", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "overworld", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "overworld", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "overworld", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "overworld", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "overworld", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "overworld", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "overworld", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "overworld", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "overworld", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "overworld", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "overworld", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "overworld", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "overworld", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "overworld", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "overworld", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "overworld", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "overworld", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "overworld", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "overworld", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "overworld", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "overworld", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "overworld", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "overworld", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "overworld", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "overworld", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "overworld", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "overworld", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "overworld", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "overworld", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "overworld", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "overworld", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "overworld", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "overworld", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "overworld", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "overworld", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "overworld", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "overworld", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "overworld", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "overworld", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "overworld", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "overworld", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "overworld", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "overworld", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "overworld", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "overworld", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "overworld", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "overworld", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "overworld", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "overworld", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "overworld", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "overworld", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "overworld", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "overworld", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "overworld", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "overworld", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "overworld", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "overworld", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "overworld", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "overworld", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "overworld", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "overworld", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "overworld", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "overworld", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "overworld", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "overworld", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "overworld", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "overworld", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "overworld", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "overworld", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "overworld", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "overworld", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "overworld", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "overworld", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "overworld", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "overworld", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "overworld", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "overworld", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "overworld", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "overworld", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "overworld", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "overworld", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "overworld", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "overworld", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "overworld", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "overworld", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "overworld", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "overworld", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "overworld", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "overworld", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "overworld", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "overworld", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "overworld", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "overworld", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "overworld", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "overworld", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "overworld", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "overworld", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "overworld", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "overworld", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "the_end", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "the_end", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "the_end", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "the_end", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "the_end", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "the_end", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "the_end", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "the_end", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "the_end", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "the_end", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "the_end", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "the_end", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "the_end", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "the_end", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "the_end", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "the_end", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "the_end", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "the_end", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "the_end", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "the_end", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "the_end", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "the_end", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "the_end", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "the_end", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "the_end", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "the_end", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "the_end", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "the_end", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "the_end", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "the_end", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "the_end", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "the_end", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "the_end", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "the_end", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "the_end", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "the_end", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "the_end", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "the_end", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "the_end", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "the_end", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "the_end", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "the_end", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "the_end", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "the_end", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "the_end", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "the_end", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "the_end", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "the_end", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "the_end", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "the_end", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "the_end", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "the_end", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "the_end", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "the_end", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "the_end", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "the_end", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "the_end", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "the_end", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "the_end", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "the_end", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "the_end", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "the_end", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "the_end", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "the_end", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "the_end", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "the_end", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "the_end", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "the_end", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "the_end", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "the_end", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "the_end", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "the_end", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "the_end", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "the_end", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "the_end", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "the_end", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "the_end", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "the_end", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "the_end", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "the_end", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "the_end", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "the_end", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "the_end", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "the_end", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "the_end", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "the_end", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "the_end", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "the_end", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "the_end", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "the_end", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "the_end", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "the_end", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "the_end", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "the_end", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "the_end", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "the_end", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "the_end", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "the_end", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "the_end", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "the_end", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "the_end", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "the_end", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "the_end", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "the_end", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "the_end", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "the_end", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "the_end", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "the_end", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "the_end", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "the_end", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "the_end", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "the_end", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "the_end", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "the_end", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "the_end", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "the_end", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "the_end", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "the_end", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "the_end", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "the_end", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "the_end", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "the_end", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "the_end", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "the_end", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "the_end", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "the_end", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "the_end", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "the_end", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "the_end", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "the_end", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "the_end", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "the_end", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "the_end", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "the_end", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "the_end", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "the_end", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "the_end", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "the_end", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "the_end", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "the_end", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "the_end", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "the_end", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "the_end", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "the_end", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "the_end", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "the_end", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "the_end", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "the_end", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "the_end", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "the_end", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "the_end", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "the_end", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "the_end", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "the_end", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "the_end", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "the_end", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "the_end", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "the_end", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "the_end", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "the_end", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "the_end", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "the_end", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "the_end", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "the_end", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "the_end", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "the_end", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "the_end", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "the_end", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "the_end", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "the_end", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "the_end", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "the_end", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "the_end", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "the_end", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "the_end", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "the_end", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "the_end", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "the_end", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "the_end", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "the_end", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "the_end", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "the_end", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "the_end", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "the_end", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "the_end", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "the_end", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "the_end", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "the_end", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "the_end", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "the_end", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "the_end", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "the_end", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "the_end", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "the_end", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "the_end", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "the_end", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "the_end", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "the_end", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "the_end", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "the_end", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "the_end", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "the_end", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "the_end", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "the_end", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "the_end", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "the_end", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "the_end", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "the_end", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "the_end", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "nether", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "nether", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "nether", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "nether", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "nether", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "nether", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "nether", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "nether", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "nether", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "nether", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "nether", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "nether", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "nether", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "nether", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "nether", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "nether", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "nether", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "nether", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "nether", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "nether", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "nether", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "nether", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "nether", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "nether", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "nether", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "nether", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "nether", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "nether", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "nether", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "nether", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "nether", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "nether", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "nether", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "nether", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "nether", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "nether", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "nether", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "nether", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "nether", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "nether", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "nether", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "nether", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "nether", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "nether", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "nether", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "nether", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "nether", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "nether", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "nether", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "nether", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "nether", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "nether", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "nether", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "nether", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "nether", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "nether", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "nether", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "nether", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "nether", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "nether", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "nether", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "nether", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "nether", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "nether", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "nether", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "nether", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "nether", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "nether", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "nether", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "nether", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "nether", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "nether", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "nether", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "nether", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "nether", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "nether", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "nether", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "nether", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "nether", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "nether", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "nether", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "nether", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "nether", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "nether", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "nether", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "nether", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "nether", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "nether", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "nether", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "nether", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "nether", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "nether", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "nether", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "nether", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "nether", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "nether", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "nether", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "nether", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "nether", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "nether", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "nether", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "nether", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "nether", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "nether", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "nether", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "nether", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "nether", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "nether", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "nether", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "nether", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "nether", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "nether", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "nether", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "nether", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "nether", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "nether", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "nether", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "nether", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "nether", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "nether", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "nether", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "nether", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "nether", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "nether", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "nether", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "nether", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "nether", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "nether", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "nether", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "nether", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "nether", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "nether", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "nether", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "nether", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "nether", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "nether", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "nether", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "nether", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "nether", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "nether", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "nether", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "nether", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "nether", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "nether", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ],
        [ "nether", "structure", -1024, -1024, "Location 0", "ffffff", "/placeIcon0.png", 100 ],
        [ "nether", "user", null, null, "Location 1", "ffffff", "/placeIcon1.png", 100 ],
        [ "nether", "structure", null, null, "Location 2", "ffffff", "/placeIcon2.png", 100 ],
        [ "nether", "user", -512, null, "Location 3", "ffffff", "/placeIcon3.png", 100 ],
        [ "nether", "structure", null, null, "Location 4", "ffffff", "/placeIcon4.png", 100 ],
        [ "nether", "user", null, null, "Location 5", "ffffff", "/placeIcon5.png", 100 ],
        [ "nether", "structure", 0, null, "Location 6", "ffffff", "/placeIcon6.png", 100 ],
        [ "nether", "user", null, null, "Location 7", "ffffff", "/placeIcon7.png", 100 ],
        [ "nether", "structure", null, null, "Location 8", "ffffff", "/placeIcon8.png", 100 ],
        [ "nether", "user", 512, null, "Location 9", "ffffff", "/placeIcon9.png", 100 ],
        [ "nether", "structure", null, null, "Location 10", "ffffff", "/placeIcon10.png", 100 ],
        [ "nether", "user", null, null, "Location 11", "ffffff", "/placeIcon11.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 12", "ffffff", "/placeIcon12.png", 100 ],
        [ "nether", "user", null, null, "Location 13", "ffffff", "/placeIcon13.png", 100 ],
        [ "nether", "structure", null, null, "Location 14", "ffffff", "/placeIcon14.png", 100 ],
        [ "nether", "user", -1024, -512, "Location 15", "ffffff", "/placeIcon15.png", 100 ],
        [ "nether", "structure", null, null, "Location 16", "ffffff", "/placeIcon16.png", 100 ],
        [ "nether", "user", null, null, "Location 17", "ffffff", "/placeIcon17.png", 100 ],
        [ "nether", "structure", -512, null, "Location 18", "ffffff", "/placeIcon18.png", 100 ],
        [ "nether", "user", null, null, "Location 19", "ffffff", "/placeIcon19.png", 100 ],
        [ "nether", "structure", null, null, "Location 20", "ffffff", "/placeIcon20.png", 100 ],
        [ "nether", "user", 0, null, "Location 21", "ffffff", "/placeIcon21.png", 100 ],
        [ "nether", "structure", null, null, "Location 22", "ffffff", "/placeIcon22.png", 100 ],
        [ "nether", "user", null, null, "Location 23", "ffffff", "/placeIcon23.png", 100 ],
        [ "nether", "structure", 512, null, "Location 24", "ffffff", "/placeIcon24.png", 100 ],
        [ "nether", "user", null, null, "Location 25", "ffffff", "/placeIcon25.png", 100 ],
        [ "nether", "structure", null, null, "Location 26", "ffffff", "/placeIcon26.png", 100 ],
        [ "nether", "user", 1024, null, "Location 27", "ffffff", "/placeIcon27.png", 100 ],
        [ "nether", "structure", null, null, "Location 28", "ffffff", "/placeIcon28.png", 100 ],
        [ "nether", "user", null, null, "Location 29", "ffffff", "/placeIcon29.png", 100 ],
        [ "nether", "structure", -1024, 0, "Location 30", "ffffff", "/placeIcon30.png", 100 ],
        [ "nether", "user", null, null, "Location 31", "ffffff", "/placeIcon31.png", 100 ],
        [ "nether", "structure", null, null, "Location 32", "ffffff", "/placeIcon32.png", 100 ],
        [ "nether", "user", -512, null, "Location 33", "ffffff", "/placeIcon33.png", 100 ],
        [ "nether", "structure", null, null, "Location 34", "ffffff", "/placeIcon34.png", 100 ],
        [ "nether", "user", null, null, "Location 35", "ffffff", "/placeIcon35.png", 100 ],
        [ "nether", "structure", 0, null, "Location 36", "ffffff", "/placeIcon36.png", 100 ],
        [ "nether", "user", null, null, "Location 37", "ffffff", "/placeIcon37.png", 100 ],
        [ "nether", "structure", null, null, "Location 38", "ffffff", "/placeIcon38.png", 100 ],
        [ "nether", "user", 512, null, "Location 39", "ffffff", "/placeIcon39.png", 100 ],
        [ "nether", "structure", null, null, "Location 40", "ffffff", "/placeIcon40.png", 100 ],
        [ "nether", "user", null, null, "Location 41", "ffffff", "/placeIcon41.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 42", "ffffff", "/placeIcon42.png", 100 ],
        [ "nether", "user", null, null, "Location 43", "ffffff", "/placeIcon43.png", 100 ],
        [ "nether", "structure", null, null, "Location 44", "ffffff", "/placeIcon44.png", 100 ],
        [ "nether", "user", -1024, 512, "Location 45", "ffffff", "/placeIcon45.png", 100 ],
        [ "nether", "structure", null, null, "Location 46", "ffffff", "/placeIcon46.png", 100 ],
        [ "nether", "user", null, null, "Location 47", "ffffff", "/placeIcon47.png", 100 ],
        [ "nether", "structure", -512, null, "Location 48", "ffffff", "/placeIcon48.png", 100 ],
        [ "nether", "user", null, null, "Location 49", "ffffff", "/placeIcon49.png", 100 ],
        [ "nether", "structure", null, null, "Location 50", "ffffff", "/placeIcon50.png", 100 ],
        [ "nether", "user", 0, null, "Location 51", "ffffff", "/placeIcon51.png", 100 ],
        [ "nether", "structure", null, null, "Location 52", "ffffff", "/placeIcon52.png", 100 ],
        [ "nether", "user", null, null, "Location 53", "ffffff", "/placeIcon53.png", 100 ],
        [ "nether", "structure", 512, null, "Location 54", "ffffff", "/placeIcon54.png", 100 ],
        [ "nether", "user", null, null, "Location 55", "ffffff", "/placeIcon55.png", 100 ],
        [ "nether", "structure", null, null, "Location 56", "ffffff", "/placeIcon56.png", 100 ],
        [ "nether", "user", 1024, null, "Location 57", "ffffff", "/placeIcon57.png", 100 ],
        [ "nether", "structure", null, null, "Location 58", "ffffff", "/placeIcon58.png", 100 ],
        [ "nether", "user", null, null, "Location 59", "ffffff", "/placeIcon59.png", 100 ],
        [ "nether", "structure", -1024, 1024, "Location 60", "ffffff", "/placeIcon60.png", 100 ],
        [ "nether", "user", null, null, "Location 61", "ffffff", "/placeIcon61.png", 100 ],
        [ "nether", "structure", null, null, "Location 62", "ffffff", "/placeIcon62.png", 100 ],
        [ "nether", "user", -512, null, "Location 63", "ffffff", "/placeIcon63.png", 100 ],
        [ "nether", "structure", null, null, "Location 64", "ffffff", "/placeIcon64.png", 100 ],
        [ "nether", "user", null, null, "Location 65", "ffffff", "/placeIcon65.png", 100 ],
        [ "nether", "structure", 0, null, "Location 66", "ffffff", "/placeIcon66.png", 100 ],
        [ "nether", "user", null, null, "Location 67", "ffffff", "/placeIcon67.png", 100 ],
        [ "nether", "structure", null, null, "Location 68", "ffffff", "/placeIcon68.png", 100 ],
        [ "nether", "user", 512, null, "Location 69", "ffffff", "/placeIcon69.png", 100 ],
        [ "nether", "structure", null, null, "Location 70", "ffffff", "/placeIcon70.png", 100 ],
        [ "nether", "user", null, null, "Location 71", "ffffff", "/placeIcon71.png", 100 ],
        [ "nether", "structure", 1024, null, "Location 72", "ffffff", "/placeIcon72.png", 100 ],
        [ "nether", "user", null, null, "Location 73", "ffffff", "/placeIcon73.png", 100 ],
        [ "nether", "structure", null, null, "Location 74", "ffffff", "/placeIcon74.png", 100 ]
    ],
    "location_categories": [ [ "structure", "Structure", "/structure.png", 100 ],
        [ "user", "User-added", "/user.png", 100 ]
    ],
    "map_types": [ [ "biome", "Biome", "/Biome./png", 100 ],
        [ "total_activity", "Total Activity", "/Total Activity./png", 100 ],
        [ "recent_activity", "Recent Activity", "/Recent Activity./png", 100 ]
    ],
    "regions": [ [ "overworld", "Overworld", "/Overworld.png", 100 ],
        [ "the_end", "The End", "/The End.png", 100 ],
        [ "nether", "Nether", "/Nether.png", 100 ]
    ],
    "tile_sizes": [ [ 128 ],
        [ 256 ],
        [ 512 ]
    ],
    "key_items_staging": [ [ "nether", "recent_activity", "First key item", 100, "ffffff", null ],
        [ "nether", "recent_activity", "Second key item", 100, null, "icon.png" ],
        [ "nether", "recent_activity", "Third key item", 100, "00ff00", null ]
    ],
    "key_items": [ [ "nether", "recent_activity", "First key item", 100, "ffffff", null ],
        [ "nether", "recent_activity", "Second key item", 100, null, "icon.png" ],
        [ "nether", "recent_activity", "Third key item", 100, "00ff00", null ]
    ],
    "map_tiles": [ [ "nether", "recent_activity", 128, -1024, -1024, "-1024_-1024.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, -512, "-1024_-512.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, 0, "-1024_0.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, 512, "-1024_512.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, 1024, "-1024_1024.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ]
    ],
    "map_tiles_staging": [ [ "nether", "recent_activity", 128, -1024, -1024, "-1024_-1024.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, -512, "-1024_-512.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, 0, "-1024_0.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, 512, "-1024_512.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -1024, 1024, "-1024_1024.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, -512, null, "-512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 0, null, "0_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 512, null, "512_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 128, 1024, null, "1024_undefined.png", 100 ],
        [ "nether", "recent_activity", 256, null, null, "undefined_undefined.png", 100 ],
        [ "nether", "recent_activity", 512, null, null, "undefined_undefined.png", 100 ]
    ]
};